"""Make username unique and not nullable

Revision ID: 2ef6f9f1c498
Revises: f450cffd23fd
Create Date: 2024-08-20 17:23:08.987443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef6f9f1c498'
down_revision: Union[str, None] = 'f450cffd23fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
