"""Make first_name, last_name, and username non-nullable

Revision ID: f450cffd23fd
Revises: d7baba5a92c2
Create Date: 2024-08-20 17:07:16.712493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f450cffd23fd'
down_revision: Union[str, None] = 'd7baba5a92c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
